### ISSUE TITLE
CAMELYON16 dataset

### ISSUE THREAD

**Issue by caruofc** [ninatu/anomaly_detection#3]
I am having a hard time downloading the CAMELYON16 dataset. Can anyone please provide a source from where you could download the dataset? Thanks.

**Comment by ninatu** [comment]
Hi! I downloaded it from google drive by the links provided on [the official challenge website](https://camelyon17.grand-challenge.org/Data/ ).

**Comment by ninatu** [comment]
I took a look and it seems like the links are hidden from webpage now, but you can take a look at [cached version of webpage](https://webcache.googleusercontent.com/search?q=cache:qG7vQGmGw7AJ:https://camelyon17.grand-challenge.org/Data/&cd=1&hl=en&ct=clnk&gl=de)

**Comment by caruofc** [comment]
Thanks you for your prompt reply! Really appreciate it.
